name: Add firmware links to pull request
on:
  workflow_run:
    workflows: [Firmware pull request validation]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add artifact links to pull request
    runs-on: windows-2019
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: workflow artifact pull request comment
        #uses: veitbjarsch/artifacts-url-comments@v1.2.0
        uses: tonyhallett/artifacts-url-comments@v1.1.0    
      #- uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "Firmware for this pull request:"
          suffix: "name: {name} "
          format: "[{name}_firmware.zip]({url})"
          #format: "[Firmware.zip]({url})"
          addTo: pull

          # Name will result in [name](url)
          # The final format is custom and is a format string 
          # e.g Whatever ({name})[{url}] etc






          ##
